services:
  postgres:
    image: postgres:15-alpine
    container_name: instagram_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: instagram_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - instagram_network

volumes:
  postgres_data:

networks:
  instagram_network:
    driver: bridge
